permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 把球给22号
  email: zdzzyc@gmail.com
  link: http://zcwk.github.io
  weibo: http://weibo.com/2739450712
  github: http://github.com/zcwk

# 站点信息
title: 把球给22号的博客 
description: 把球给22号的博客
url: http://zcwk.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://avatars2.githubusercontent.com/u/6406512?v=3&u=e1c9820d844105212f65220b3134d66d8eff42aa&s=140
favicon: https://avatars2.githubusercontent.com/u/6406512?v=3&u=e1c9820d844105212f65220b3134d66d8eff42aa&s=140

# google analytics 设置
ga:
  id: UA-54767140-1
  url: zcwk.github.io

# disqus 设置
disqus:
  shortname: zwck